import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  Table,
  TableRow,
  TableCell,
  WidthType,
  BorderStyle,
  AlignmentType,
  TableOfContents,
  ShadingType,
} from "docx";
import { saveAs } from "file-saver";

function h1(text: string) {
  return new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text, bold: true, size: 32, font: "微软雅黑" })] });
}
function h2(text: string) {
  return new Paragraph({ heading: HeadingLevel.HEADING_2, spacing: { before: 240, after: 120 }, children: [new TextRun({ text, bold: true, size: 28, font: "微软雅黑" })] });
}
function h3(text: string) {
  return new Paragraph({ heading: HeadingLevel.HEADING_3, spacing: { before: 200, after: 80 }, children: [new TextRun({ text, bold: true, size: 24, font: "微软雅黑" })] });
}
function p(text: string, bold = false) {
  return new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text, size: 21, font: "宋体", bold })] });
}
function bullet(text: string, level = 0) {
  return new Paragraph({ bullet: { level }, spacing: { after: 60 }, children: [new TextRun({ text, size: 21, font: "宋体" })] });
}
function code(text: string) {
  return new Paragraph({
    spacing: { after: 40 },
    children: [new TextRun({ text, size: 18, font: "Consolas", color: "2d2d2d" })],
    shading: { type: ShadingType.SOLID, color: "f5f5f5", fill: "f5f5f5" },
  });
}
function tableCell(text: string, bold = false, shading?: string) {
  return new TableCell({
    children: [new Paragraph({ children: [new TextRun({ text, size: 20, font: "宋体", bold })] })],
    width: { size: 100, type: WidthType.AUTO },
    ...(shading ? { shading: { type: ShadingType.SOLID, color: shading, fill: shading } } : {}),
  });
}

export async function exportBidParserDesignDoc() {
  const doc = new Document({
    styles: {
      default: {
        document: { run: { size: 21, font: "宋体" } },
      },
    },
    sections: [
      {
        children: [
          // ===== 封面 =====
          new Paragraph({ spacing: { before: 2400 }, alignment: AlignmentType.CENTER, children: [new TextRun({ text: "招标解析模块", bold: true, size: 52, font: "微软雅黑" })] }),
          new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 200 }, children: [new TextRun({ text: "详细设计说明书", size: 36, font: "微软雅黑", color: "555555" })] }),
          new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 600 }, children: [new TextRun({ text: "润和捷科AI智标工厂", size: 24, font: "微软雅黑", color: "888888" })] }),
          new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 200 }, children: [new TextRun({ text: `文档版本: V1.0  |  日期: ${new Date().toISOString().split("T")[0]}`, size: 20, font: "宋体", color: "999999" })] }),
          new Paragraph({ spacing: { before: 1200 }, children: [] }),

          // ===== 1. 概述 =====
          h1("1. 模块概述"),
          p("招标解析模块（BidParser）是AI智标工厂的核心功能之一，负责对用户上传的招标文件进行自动化智能解析。系统采用两阶段解析架构：先提取文档整体结构（章节目录树），经用户确认后再进行逐章节的详细解析，最终输出14项结构化招标数据。"),
          p(""),

          h2("1.1 功能定位"),
          bullet("将非结构化的招标文件（PDF/DOCX/DOC/Excel）转化为结构化的可操作数据"),
          bullet("自动识别废标项、陷阱项、逻辑冲突、评分标准、人员要求等关键信息"),
          bullet("为后续投标助手、标书组装等模块提供基础数据支撑"),
          p(""),

          h2("1.2 支持的文件格式"),
          new Table({
            rows: [
              new TableRow({ children: [tableCell("格式", true, "e8e8e8"), tableCell("扩展名", true, "e8e8e8"), tableCell("解析方式", true, "e8e8e8"), tableCell("大小限制", true, "e8e8e8")] }),
              new TableRow({ children: [tableCell("PDF"), tableCell(".pdf"), tableCell("Lovable网关原生解析 / 非Lovable回退文本提取"), tableCell("结构分析5MB, 详细分析无限制")] }),
              new TableRow({ children: [tableCell("Word (新)"), tableCell(".docx"), tableCell("ZIP解压 → word/document.xml → 正则提取段落"), tableCell("结构分析5MB")] }),
              new TableRow({ children: [tableCell("Word (旧)"), tableCell(".doc"), tableCell("OLE2格式 → word-extractor库解析"), tableCell("无")] }),
              new TableRow({ children: [tableCell("Excel"), tableCell(".xlsx / .xls"), tableCell("xlsx库解析 → sheet_to_csv转文本"), tableCell("无")] }),
            ],
            width: { size: 100, type: WidthType.PERCENTAGE },
          }),
          p(""),

          // ===== 2. 系统架构 =====
          h1("2. 系统架构"),

          h2("2.1 两阶段解析架构"),
          p("招标解析采用\u201C先结构后详情\u201D的两步走策略，核心原因是："),
          bullet("招标文件通常篇幅巨大（数十至数百页），一次性解析容易超出AI上下文窗口"),
          bullet("先让用户确认结构正确性，可以避免在错误结构上浪费AI算力"),
          bullet("分阶段处理允许用户自定义解析重点，提高针对性"),
          p(""),

          p("第一阶段：结构分析 (parse-bid-structure)", true),
          bullet("输入：招标文件（文件上传或文本粘贴）"),
          bullet("处理：AI识别文档所有章节，构建完整目录树"),
          bullet("输出：DocumentStructure对象，包含章节编号、标题、重要程度、页码提示"),
          bullet("通信方式：HTTP POST → 后台异步处理 → 前端轮询数据库获取结果"),
          p(""),

          p("第二阶段：详细解析 (parse-bid)", true),
          bullet("输入：文件 + 第一阶段的结构信息 + 用户自定义解析清单"),
          bullet("处理：AI结合结构上下文，逐章节提取14项结构化数据"),
          bullet("输出：评分表、废标项、陷阱项、逻辑冲突、关键词、人员要求等"),
          bullet("通信方式：SSE（Server-Sent Events）流式响应 + 15秒心跳包"),
          p(""),

          h2("2.2 整体数据流"),
          code("用户上传文件 → Supabase Storage (knowledge-base bucket)"),
          code("  ↓"),
          code("前端调用 parse-bid-structure Edge Function"),
          code("  ↓"),
          code("Edge Function 下载文件 → 提取文本/原生传输 → 调用AI Gateway"),
          code("  ↓"),
          code("AI 返回 Tool Call (extract_document_structure) → 写入 bid_analyses.document_structure"),
          code("  ↓"),
          code("前端轮询检测 ai_status = 'structure_ready' → 展示结构树"),
          code("  ↓"),
          code("用户确认 → 前端调用 parse-bid Edge Function"),
          code("  ↓"),
          code("Edge Function 下载文件 → 注入结构上下文到System Prompt → 调用AI"),
          code("  ↓"),
          code("AI 返回 Tool Call (analyze_bid_document) → 14项数据写入 bid_analyses"),
          code("  ↓"),
          code("前端轮询检测 ai_status = 'completed' → 渲染6个标签页结果"),
          p(""),

          h2("2.3 涉及的Edge Function清单"),
          new Table({
            rows: [
              new TableRow({ children: [tableCell("函数名", true, "e8e8e8"), tableCell("职责", true, "e8e8e8"), tableCell("通信方式", true, "e8e8e8"), tableCell("超时", true, "e8e8e8")] }),
              new TableRow({ children: [tableCell("parse-bid-structure"), tableCell("第一阶段：文档结构分析"), tableCell("HTTP POST + 后台异步"), tableCell("无（后台处理）")] }),
              new TableRow({ children: [tableCell("parse-bid"), tableCell("第二阶段：详细内容解析"), tableCell("SSE流式 + 15s心跳"), tableCell("AI请求无显式超时")] }),
              new TableRow({ children: [tableCell("extract-bid-chapters"), tableCell("辅助：章节文本切分"), tableCell("HTTP POST同步"), tableCell("120s (AbortController)")] }),
            ],
            width: { size: 100, type: WidthType.PERCENTAGE },
          }),
          p(""),

          // ===== 3. 状态机设计 =====
          h1("3. 状态机设计"),

          h2("3.1 ai_status 状态枚举"),
          new Table({
            rows: [
              new TableRow({ children: [tableCell("状态值", true, "e8e8e8"), tableCell("含义", true, "e8e8e8"), tableCell("触发条件", true, "e8e8e8"), tableCell("可转移到", true, "e8e8e8")] }),
              new TableRow({ children: [tableCell("pending"), tableCell("待处理"), tableCell("创建记录时默认"), tableCell("analyzing_structure")] }),
              new TableRow({ children: [tableCell("analyzing_structure"), tableCell("正在分析结构"), tableCell("调用parse-bid-structure"), tableCell("structure_ready, failed, paused_structure, cancelled")] }),
              new TableRow({ children: [tableCell("structure_ready"), tableCell("结构分析完成"), tableCell("AI返回有效结构数据"), tableCell("processing, analyzing_structure")] }),
              new TableRow({ children: [tableCell("processing"), tableCell("详细解析中"), tableCell("调用parse-bid"), tableCell("completed, failed, structure_ready, paused, cancelled")] }),
              new TableRow({ children: [tableCell("completed"), tableCell("解析完成"), tableCell("AI返回有效解析数据"), tableCell("analyzing_structure（重新解析）")] }),
              new TableRow({ children: [tableCell("failed"), tableCell("解析失败"), tableCell("AI错误/文件格式错误等"), tableCell("analyzing_structure（重试）")] }),
              new TableRow({ children: [tableCell("timeout"), tableCell("超时"), tableCell("前端检测>2分钟无更新"), tableCell("analyzing_structure（重试）")] }),
              new TableRow({ children: [tableCell("paused"), tableCell("详细解析已暂停"), tableCell("用户点击暂停"), tableCell("processing（继续）, cancelled")] }),
              new TableRow({ children: [tableCell("paused_structure"), tableCell("结构分析已暂停"), tableCell("用户点击暂停"), tableCell("analyzing_structure（继续）, cancelled")] }),
              new TableRow({ children: [tableCell("cancelled"), tableCell("已取消"), tableCell("用户退出解析"), tableCell("analyzing_structure（重新开始）")] }),
            ],
            width: { size: 100, type: WidthType.PERCENTAGE },
          }),
          p(""),

          h2("3.2 结构保护机制"),
          p("当详细解析（第二阶段）失败时，系统不会将状态回退到 failed，而是保持 structure_ready，让用户可以直接重试详细解析而无需重新分析结构。具体逻辑："),
          code("if (existing?.document_structure) {"),
          code("  // 有结构数据 → 回退到 structure_ready，保护第一阶段成果"),
          code("  update({ ai_status: 'structure_ready', ai_progress: '详细解析失败...' })"),
          code("} else {"),
          code("  // 无结构数据 → 标记为 failed"),
          code("  update({ ai_status: 'failed' })"),
          code("}"),
          p(""),

          // ===== 4. 前端详细设计 =====
          h1("4. 前端详细设计 (BidParser.tsx)"),

          h2("4.1 组件概览"),
          p("BidParser.tsx 是招标解析模块的核心前端组件，共约1480行代码。负责文件上传、解析触发、状态轮询、结果展示的完整交互流程。"),
          p(""),

          h2("4.2 核心状态变量"),
          new Table({
            rows: [
              new TableRow({ children: [tableCell("变量", true, "e8e8e8"), tableCell("类型", true, "e8e8e8"), tableCell("用途", true, "e8e8e8")] }),
              new TableRow({ children: [tableCell("analyses"), tableCell("BidAnalysis[]"), tableCell("所有解析记录列表")] }),
              new TableRow({ children: [tableCell("selectedAnalysis"), tableCell("BidAnalysis | null"), tableCell("当前选中的解析记录详情")] }),
              new TableRow({ children: [tableCell("analyzing"), tableCell("boolean"), tableCell("是否正在进行结构分析")] }),
              new TableRow({ children: [tableCell("detailParsing"), tableCell("boolean"), tableCell("是否正在进行详细解析")] }),
              new TableRow({ children: [tableCell("reAnalyzing"), tableCell("boolean"), tableCell("是否正在重新分析")] }),
              new TableRow({ children: [tableCell("inputMode"), tableCell("'file' | 'text'"), tableCell("输入方式：文件上传 or 文本粘贴")] }),
              new TableRow({ children: [tableCell("uploadedFiles"), tableCell("File[]"), tableCell("已选择的待上传文件列表")] }),
              new TableRow({ children: [tableCell("customPrompt"), tableCell("string"), tableCell("用户自定义解析清单（8条默认指令）")] }),
              new TableRow({ children: [tableCell("tokenUsage"), tableCell("object | null"), tableCell("AI Token 使用量统计")] }),
              new TableRow({ children: [tableCell("aiProgress"), tableCell("string | null"), tableCell("当前AI处理进度文本")] }),
            ],
            width: { size: 100, type: WidthType.PERCENTAGE },
          }),
          p(""),

          h2("4.3 SSE 流式通信 (invokeWithStreaming)"),
          p("前端通过 fetch API 直接调用 Edge Function，支持两种响应模式："),
          bullet("text/event-stream：读取 SSE 流，解析 data: 行中的 JSON 事件"),
          bullet("application/json：后台异步处理，消费响应体后等待轮询"),
          p(""),
          p("SSE事件类型："),
          bullet("progress — 进度消息，更新 aiProgress 状态显示给用户"),
          bullet("heartbeat — 每15秒心跳，保持HTTP连接不被网关/代理断开"),
          bullet("error — 错误消息"),
          bullet("complete — 解析完成信号"),
          p(""),

          h2("4.4 数据库轮询 (startTokenPolling)"),
          p("由于AI处理耗时较长（可达数十秒甚至数分钟），前端采用3秒间隔轮询数据库的方式同步状态："),
          code("tokenPollRef.current = setInterval(async () => {"),
          code("  const { data } = await supabase"),
          code("    .from('bid_analyses').select('*').eq('id', analysisId).single();"),
          code("  "),
          code("  // 更新Token使用量"),
          code("  if (data?.token_usage) setTokenUsage(data.token_usage);"),
          code("  "),
          code("  // 更新进度文本"),
          code("  if (data?.ai_progress) setAiProgress(data.ai_progress);"),
          code("  "),
          code("  // 检测完成状态 → 停止轮询，触发回调"),
          code("  if (!['analyzing_structure', 'processing'].includes(data.ai_status)) {"),
          code("    stopTokenPolling();"),
          code("    onComplete(data);"),
          code("  }"),
          code("}, 3000);"),
          p(""),

          h2("4.5 超时检测"),
          p("前端在加载解析列表时，自动检测长时间未更新的任务："),
          bullet("检测条件：ai_status 为 processing/analyzing_structure，且 updated_at 距今超过2分钟"),
          bullet("处理方式：自动将 ai_status 更新为 timeout"),
          bullet("用户可通过"重新解析"按钮从 timeout 状态恢复"),
          p(""),

          h2("4.6 文件上传流程"),
          p("多文件上传支持：用户可一次选择多个招标文件，系统逐一处理。"),
          bullet("1. 生成安全文件名：`${Date.now()}_${random}.${ext}` 避免文件名冲突和中文路径问题"),
          bullet("2. 上传到 Supabase Storage 的 knowledge-base bucket，路径为 `${user.id}/${safeFileName}`"),
          bullet("3. 在 bid_analyses 表插入记录，关联 file_path"),
          bullet("4. 如未输入项目名，自动从文件名提取（去掉扩展名）"),
          bullet("5. 调用 parse-bid-structure 开始第一阶段分析"),
          p(""),

          h2("4.7 结果展示（6个标签页）"),
          p("详细解析完成后，结果以6个标签页形式展示："),
          p(""),
          p("标签页1：废标项 (disqualification)", true),
          bullet("左侧红色竖线标识，严重度分三级：必废标(critical)、极高风险(high)、较高风险(medium)"),
          bullet("显示原文引用（斜体灰色背景），方便核对"),
          p(""),
          p("标签页2：陷阱项 (traps)", true),
          bullet("三级风险标签：高/中/低"),
          bullet("包含问题描述和建议措施（💡 浅色背景提示框）"),
          p(""),
          p("标签页3：逻辑冲突 (conflicts)", true),
          bullet("紫色视觉主题，左侧紫色竖线"),
          bullet("显示冲突详情、出现位置"),
          p(""),
          p("标签页4：评分标准表 (scoring)", true),
          bullet("表格形式：分类 | 评分项 | 分值 | 评分细则 | 佐证材料"),
          p(""),
          p("标签页5：关键词 (keywords)", true),
          bullet("三类关键词：专业技能（蓝色）、业务技能（绿色）、工作职责（紫色）"),
          bullet("Badge 标签展示，便于快速浏览"),
          p(""),
          p("标签页6：人员要求 (personnel)", true),
          bullet("卡片式展示每个角色要求：角色名、数量、资质、证书、经验年限、特殊要求"),
          p(""),

          h2("4.8 顶部元数据汇总栏"),
          p("解析完成后，详情页头部显示4项核心元数据："),
          bullet("📅 投标截止时间（红色高亮）"),
          bullet("📍 投标/开标地点（蓝色高亮）"),
          bullet("✅/❌ 是否需要讲标"),
          bullet("💰 投标保证金金额（琥珀色高亮）"),
          p("右上角显示风险评分（0-100），颜色随分值变化：≥70红色, ≥40橙色, <40绿色"),
          p(""),

          // ===== 5. 后端详细设计 =====
          h1("5. 后端详细设计"),

          h2("5.1 parse-bid-structure (第一阶段)"),
          p("文件位置: supabase/functions/parse-bid-structure/index.ts (约414行)", true),
          p(""),

          h3("5.1.1 处理流程"),
          bullet("1. 接收参数：analysisId, filePath, fileType, content, projectName"),
          bullet("2. 读取 model_config 表获取AI模型配置（支持自定义模型）"),
          bullet("3. 更新 ai_status 为 analyzing_structure"),
          bullet("4. 从 Storage 下载文件并检测格式"),
          bullet("5. 根据文件类型选择处理策略（见5.1.2）"),
          bullet("6. 构建消息发送给AI，要求使用 extract_document_structure 工具"),
          bullet("7. 解析AI返回的Tool Call参数，写入 document_structure 字段"),
          bullet("8. 更新 ai_status 为 structure_ready"),
          p(""),

          h3("5.1.2 文件格式处理策略"),
          p("PDF文件（Lovable网关模式）：", true),
          bullet("将ArrayBuffer转为Base64"),
          bullet("通过 file 类型的 content part 原生传送给AI"),
          bullet("格式：{ type: 'file', file: { filename, file_data: 'data:application/pdf;base64,...' } }"),
          p(""),
          p("PDF文件（非Lovable模式）：", true),
          bullet("尝试从PDF原始字节中用正则提取文本：/\\(([^)]{1,500})\\)/g"),
          bullet("解码转义字符：\\n → 换行, \\\\( → ("),
          bullet("如提取文本不足200字符，提示无法提取"),
          p(""),
          p("DOCX文件：", true),
          bullet("使用内置 DecompressionStream 解压（非第三方库，节省内存）"),
          bullet("验证ZIP魔数：0x50 0x4B (PK)"),
          bullet("遍历ZIP本地文件头，定位 word/document.xml"),
          bullet("对 deflate 压缩的条目使用 DecompressionStream('deflate-raw') 解压"),
          bullet("正则提取段落：<w:p> → 换行, <w:t>text</w:t> → text"),
          bullet("文本截断上限：60,000字符"),
          p(""),
          p("Excel文件：", true),
          bullet("Lovable模式：转Base64原生传输"),
          bullet("非Lovable：使用xlsx库解析，sheet_to_csv转文本"),
          p(""),

          h3("5.1.3 后台异步处理"),
          p("为避免Edge Function 30秒超时限制，结构分析采用后台异步模式："),
          code("// 使用 EdgeRuntime.waitUntil 在后台继续处理"),
          code("if (typeof EdgeRuntime !== 'undefined' && EdgeRuntime.waitUntil) {"),
          code("  EdgeRuntime.waitUntil(processInBackground());"),
          code("} else {"),
          code("  processInBackground().catch(console.error);"),
          code("}"),
          code(""),
          code("// 立即返回HTTP响应"),
          code("return new Response(JSON.stringify({ status: 'processing', analysisId }));"),
          p(""),

          h3("5.1.4 AI Tool定义 (extract_document_structure)"),
          p("返回结构包含以下字段："),
          new Table({
            rows: [
              new TableRow({ children: [tableCell("字段", true, "e8e8e8"), tableCell("类型", true, "e8e8e8"), tableCell("说明", true, "e8e8e8")] }),
              new TableRow({ children: [tableCell("document_title"), tableCell("string"), tableCell("文档标题/项目名称")] }),
              new TableRow({ children: [tableCell("total_pages"), tableCell("integer"), tableCell("文档总页数（估计）")] }),
              new TableRow({ children: [tableCell("sections"), tableCell("array"), tableCell("章节结构树（支持嵌套children）")] }),
              new TableRow({ children: [tableCell("sections[].number"), tableCell("string"), tableCell("章节编号（如'第一章','1.2.3'）")] }),
              new TableRow({ children: [tableCell("sections[].title"), tableCell("string"), tableCell("章节标题")] }),
              new TableRow({ children: [tableCell("sections[].importance"), tableCell("enum"), tableCell("critical/high/medium/low")] }),
              new TableRow({ children: [tableCell("sections[].importance_reason"), tableCell("string"), tableCell("重要程度原因说明")] }),
              new TableRow({ children: [tableCell("sections[].children"), tableCell("array"), tableCell("子章节（递归同结构）")] }),
              new TableRow({ children: [tableCell("summary"), tableCell("string"), tableCell("文档整体概述（100字以内）")] }),
            ],
            width: { size: 100, type: WidthType.PERCENTAGE },
          }),
          p(""),

          h2("5.2 parse-bid (第二阶段)"),
          p("文件位置: supabase/functions/parse-bid/index.ts (约605行)", true),
          p(""),

          h3("5.2.1 处理流程"),
          bullet("1. 接收参数：analysisId, content, projectName, filePath, fileType, customPrompt, documentStructure"),
          bullet("2. 构建System Prompt：基础指令 + 文档结构注入 + 用户自定义解析重点"),
          bullet("3. 读取 model_config 获取AI配置"),
          bullet("4. 根据文件类型处理文件内容（同第一阶段，但字符上限提升至120,000）"),
          bullet("5. 通过 SSE ReadableStream 保持连接"),
          bullet("6. 15秒心跳包防止网关超时"),
          bullet("7. 调用AI Gateway发送请求"),
          bullet("8. 解析Tool Call返回的14项结构化数据"),
          bullet("9. Token使用量累加（与第一阶段合并统计）"),
          bullet("10. 写入数据库，更新 ai_status 为 completed"),
          p(""),

          h3("5.2.2 SSE流式响应实现"),
          code("const stream = new ReadableStream({"),
          code("  async start(controller) {"),
          code("    const sendEvent = (data) => {"),
          code("      controller.enqueue(encoder.encode(`data: ${JSON.stringify(data)}\\n\\n`));"),
          code("    };"),
          code(""),
          code("    // 15秒心跳保持连接"),
          code("    const heartbeat = setInterval(() => {"),
          code("      sendEvent({ type: 'heartbeat' });"),
          code("    }, 15000);"),
          code(""),
          code("    // 调用AI..."),
          code("    // 清理心跳 → 发送结果事件 → controller.close()"),
          code("  }"),
          code("});"),
          code("return new Response(stream, {"),
          code("  headers: { 'Content-Type': 'text/event-stream' }"),
          code("});"),
          p(""),

          h3("5.2.3 AI Tool定义 (analyze_bid_document)"),
          p("输出14项结构化数据："),
          new Table({
            rows: [
              new TableRow({ children: [tableCell("字段", true, "e8e8e8"), tableCell("类型", true, "e8e8e8"), tableCell("说明", true, "e8e8e8")] }),
              new TableRow({ children: [tableCell("scoring_table"), tableCell("array<object>"), tableCell("评分标准：category, item, weight, criteria, evidence_required")] }),
              new TableRow({ children: [tableCell("disqualification_items"), tableCell("array<object>"), tableCell("废标项：item, source_text, severity(critical/high/medium)")] }),
              new TableRow({ children: [tableCell("trap_items"), tableCell("array<object>"), tableCell("陷阱项：item, risk_level(high/medium/low), description, suggestion")] }),
              new TableRow({ children: [tableCell("conflict_items"), tableCell("array<object>"), tableCell("逻辑冲突：item, detail, location, severity")] }),
              new TableRow({ children: [tableCell("technical_keywords"), tableCell("string[]"), tableCell("专业技能关键词")] }),
              new TableRow({ children: [tableCell("business_keywords"), tableCell("string[]"), tableCell("业务技能关键词")] }),
              new TableRow({ children: [tableCell("responsibility_keywords"), tableCell("string[]"), tableCell("工作职责关键词")] }),
              new TableRow({ children: [tableCell("personnel_requirements"), tableCell("array<object>"), tableCell("人员要求：role, count, qualifications, certifications, experience_years")] }),
              new TableRow({ children: [tableCell("summary"), tableCell("string"), tableCell("总体分析摘要（200字以内）")] }),
              new TableRow({ children: [tableCell("risk_score"), tableCell("integer"), tableCell("风险评分0-100")] }),
              new TableRow({ children: [tableCell("bid_deadline"), tableCell("string|null"), tableCell("投标截止时间（ISO 8601格式）")] }),
              new TableRow({ children: [tableCell("bid_location"), tableCell("string|null"), tableCell("投标/开标地点")] }),
              new TableRow({ children: [tableCell("requires_presentation"), tableCell("boolean|null"), tableCell("是否需要讲标")] }),
              new TableRow({ children: [tableCell("deposit_amount"), tableCell("string|null"), tableCell("保证金金额")] }),
            ],
            width: { size: 100, type: WidthType.PERCENTAGE },
          }),
          p(""),

          h3("5.2.4 文件格式处理（详细解析阶段）"),
          p(".doc 旧格式处理：", true),
          bullet("通过 OLE2 魔数 0xD0CF11E0 检测旧Word格式"),
          bullet("使用 word-extractor npm包（1.0.4版本）提取正文"),
          bullet("需要 Node.js Buffer polyfill（Edge Function环境中默认不可用）"),
          code("import { Buffer } from 'node:buffer';"),
          code("if (typeof globalThis.Buffer === 'undefined') {"),
          code("  (globalThis as any).Buffer = Buffer;"),
          code("}"),
          p(""),
          p("DOCX 处理：", true),
          bullet("使用 fflate 库（0.8.2版本）的 unzipSync 同步解压"),
          bullet("直接读取 word/document.xml 并正则提取文本"),
          p(""),
          p("Excel 处理：", true),
          bullet("xlsx 库读取所有Sheet"),
          bullet("每个Sheet以 【Sheet: 名称】 标注后用 CSV 格式输出"),
          p(""),

          h2("5.3 extract-bid-chapters (辅助函数)"),
          p("文件位置: supabase/functions/extract-bid-chapters/index.ts (约678行)", true),
          p("此函数负责将招标文件的全文按章节切分为独立文本块。"),
          p(""),

          h3("5.3.1 三级回退章节识别策略"),
          p("Level 1: 正则TOC解析 (extractTocFromText)", true),
          bullet("搜索"目录"关键字（支持空格变体如 '目 录'、'目　录'）"),
          bullet("从目录区域提取条目，扫描范围最大50,000字符"),
          bullet("6种TOC格式正则："),
          bullet("  - 第X章/第X部分/第X节", 1),
          bullet("  - 数字编号：1.1, 1.1.1", 1),
          bullet("  - 中文数字：（一）、（二）", 1),
          bullet("  - 附录/附件编号", 1),
          bullet("  - 中文顺序：一、二、三、", 1),
          bullet("  - 无编号但带页码的条目（如 '评分导航表....5'）", 1),
          bullet("连续空行容忍度：8行（DOCX TOC常有额外间距）"),
          bullet("噪音过滤：跳过 PAGEREF、纯数字行、纯点号行"),
          p(""),
          p("Level 2: 正文扫描 (extractChaptersFromBody)", true),
          bullet("当TOC提取结果不足5条时启用"),
          bullet("扫描全文每一行，匹配6种章节标题正则模式"),
          bullet("过滤条件：行长度2-200字符，标题长度1-80字符"),
          bullet("排除日期格式（如 '2025年'、'6 月'）"),
          p(""),
          p("Level 3: AI辅助提取 (callAI)", true),
          bullet("始终执行（即使前两步有结果），取结果更多者"),
          bullet("首选模型：google/gemini-2.5-pro（120秒超时）"),
          bullet("回退模型：google/gemini-2.5-flash + 纯JSON提示词（不用Tool Call）"),
          bullet("最终回退：model_config 中用户自定义模型"),
          bullet("AI输入上限：120,000字符"),
          bullet("AI输出上限：32,768 tokens"),
          p(""),

          h3("5.3.2 章节文本切分算法 (splitTextByChapters)"),
          p("核心算法将章节标题映射到全文中的实际位置："),
          p(""),
          p("Step 1: 候选位置搜索", true),
          bullet("对每个章节，生成多种搜索模式（编号+标题，多种分隔符）"),
          bullet("使用 findAllOccurrences 搜索全文匹配"),
          bullet("同时搜索行首出现的标题 (findLineStartOccurrences)"),
          p(""),
          p("Step 2: TOC区域检测", true),
          bullet("如果前几个章节的首次出现位置非常密集（间距<200字符），认为是TOC区域"),
          bullet("记录 tocEnd 位置，后续搜索从 tocEnd 之后开始"),
          p(""),
          p("Step 3: 顺序定位", true),
          bullet("保持 minPos 单调递增，确保章节N+1在章节N之后"),
          bullet("优先使用完整匹配（编号+标题）"),
          bullet("回退使用行首标题匹配"),
          bullet("最终回退：在 tocEnd 之后搜索标题"),
          p(""),
          p("Step 4: 文本切割", true),
          bullet("每章的文本 = 从当前位置到下一章位置的全部内容"),
          bullet("最后一章延伸到文档末尾"),
          bullet("去重：相同位置的重复章节只保留一个"),
          p(""),

          h3("5.3.3 智能文本选择 (selectTextForAI)"),
          p("当全文超过AI上限时的截取策略："),
          bullet("优先策略：如果检测到目录区域，从目录前2000字符开始截取"),
          bullet("大文档策略（超过1.5倍限额）：前70% + 后30%，中间插入省略标记"),
          bullet("默认策略：截取前 maxLen 字符"),
          p(""),

          // ===== 6. JSON修复引擎 =====
          h1("6. JSON修复引擎"),
          p("AI返回的JSON经常因为Token限制被截断或格式异常。系统在三个地方实现了独立的JSON修复逻辑："),
          p(""),

          h2("6.1 parse-bid-structure 版本"),
          p("最完整的修复引擎（~55行），采用多轮修复策略："),
          bullet("Round 1: 直接 JSON.parse 尝试"),
          bullet("Round 2: 去除 markdown 代码块标记"),
          bullet("Round 3: 清理控制字符、去除尾部逗号"),
          bullet("Round 4: 字符串闭合检测 — 跟踪转义状态和引号配对"),
          bullet("Round 5: 括号平衡 — 计算未闭合的 {}/[] 并自动补齐"),
          bullet("Round 6: 截断不完整的键值对和对象"),
          bullet("Round 7: 逐位回退 — 从末尾逐字符向前寻找可解析的JSON子串"),
          p(""),

          h2("6.2 parse-bid 版本"),
          p("结构跟踪修复（~70行），使用栈模拟JSON解析器："),
          bullet("维护 stack 数组跟踪 {}/[] 嵌套"),
          bullet("处理未终止字符串（定位最后一个引号）"),
          bullet("激进截断：从末尾向前找 }/]，每个位置尝试重新平衡并解析"),
          p(""),

          h2("6.3 extract-bid-chapters 版本"),
          p("轻量级修复（~50行）："),
          bullet("尝试直接解析 → 去尾逗号 → 删除不完整属性 → 栈平衡闭合 → 寻找最后有效闭合符"),
          p(""),

          // ===== 7. AI模型配置 =====
          h1("7. AI模型配置"),

          h2("7.1 多模型路由机制"),
          p("系统支持通过 model_config 表动态切换AI模型："),
          new Table({
            rows: [
              new TableRow({ children: [tableCell("配置项", true, "e8e8e8"), tableCell("默认值", true, "e8e8e8"), tableCell("说明", true, "e8e8e8")] }),
              new TableRow({ children: [tableCell("base_url"), tableCell("https://ai.gateway.lovable.dev/v1/chat/completions"), tableCell("AI网关地址")] }),
              new TableRow({ children: [tableCell("model_name"), tableCell("google/gemini-2.5-flash"), tableCell("模型标识")] }),
              new TableRow({ children: [tableCell("api_key"), tableCell("LOVABLE_API_KEY (env)"), tableCell("认证密钥")] }),
              new TableRow({ children: [tableCell("max_tokens"), tableCell("32000 (Lovable) / 8192 (其他)"), tableCell("最大输出Token")] }),
              new TableRow({ children: [tableCell("provider"), tableCell("lovable"), tableCell("供应商标识")] }),
            ],
            width: { size: 100, type: WidthType.PERCENTAGE },
          }),
          p(""),

          h2("7.2 Lovable vs 非Lovable模式差异"),
          bullet("Tool sanitization：非Lovable模式下移除 additionalProperties 和 nullable 属性（某些模型不支持）"),
          bullet("tool_choice：Lovable强制指定函数名，非Lovable使用 auto"),
          bullet("Token参数：OpenAI系列使用 max_completion_tokens，其他使用 max_tokens"),
          bullet("文件传输：Lovable支持原生 file content part，非Lovable需提取为文本"),
          p(""),

          // ===== 8. 数据库设计 =====
          h1("8. 数据库设计"),

          h2("8.1 bid_analyses 表"),
          p("核心数据表，存储所有招标解析记录及结果："),
          new Table({
            rows: [
              new TableRow({ children: [tableCell("字段", true, "e8e8e8"), tableCell("类型", true, "e8e8e8"), tableCell("说明", true, "e8e8e8")] }),
              new TableRow({ children: [tableCell("id"), tableCell("uuid PK"), tableCell("主键")] }),
              new TableRow({ children: [tableCell("user_id"), tableCell("uuid NOT NULL"), tableCell("所属用户")] }),
              new TableRow({ children: [tableCell("project_name"), tableCell("text"), tableCell("项目名称")] }),
              new TableRow({ children: [tableCell("file_path"), tableCell("text"), tableCell("Storage中的文件路径")] }),
              new TableRow({ children: [tableCell("document_id"), tableCell("uuid FK"), tableCell("关联知识库文档")] }),
              new TableRow({ children: [tableCell("ai_status"), tableCell("text"), tableCell("状态机状态（见3.1节）")] }),
              new TableRow({ children: [tableCell("ai_progress"), tableCell("text"), tableCell("当前进度描述文本")] }),
              new TableRow({ children: [tableCell("custom_prompt"), tableCell("text"), tableCell("用户自定义解析指令")] }),
              new TableRow({ children: [tableCell("document_structure"), tableCell("jsonb"), tableCell("第一阶段结果：文档结构树")] }),
              new TableRow({ children: [tableCell("scoring_table"), tableCell("jsonb"), tableCell("评分标准表")] }),
              new TableRow({ children: [tableCell("disqualification_items"), tableCell("jsonb"), tableCell("废标项列表")] }),
              new TableRow({ children: [tableCell("trap_items"), tableCell("jsonb"), tableCell("陷阱项列表")] }),
              new TableRow({ children: [tableCell("conflict_items"), tableCell("jsonb"), tableCell("逻辑冲突项列表")] }),
              new TableRow({ children: [tableCell("technical_keywords"), tableCell("jsonb"), tableCell("专业技能关键词")] }),
              new TableRow({ children: [tableCell("business_keywords"), tableCell("jsonb"), tableCell("业务技能关键词")] }),
              new TableRow({ children: [tableCell("responsibility_keywords"), tableCell("jsonb"), tableCell("工作职责关键词")] }),
              new TableRow({ children: [tableCell("personnel_requirements"), tableCell("jsonb"), tableCell("人员配置要求")] }),
              new TableRow({ children: [tableCell("summary"), tableCell("text"), tableCell("总体分析摘要")] }),
              new TableRow({ children: [tableCell("risk_score"), tableCell("integer"), tableCell("风险评分(0-100)")] }),
              new TableRow({ children: [tableCell("bid_deadline"), tableCell("timestamptz"), tableCell("投标截止时间")] }),
              new TableRow({ children: [tableCell("bid_location"), tableCell("text"), tableCell("投标地点")] }),
              new TableRow({ children: [tableCell("requires_presentation"), tableCell("boolean"), tableCell("是否讲标")] }),
              new TableRow({ children: [tableCell("deposit_amount"), tableCell("text"), tableCell("保证金金额")] }),
              new TableRow({ children: [tableCell("token_usage"), tableCell("jsonb"), tableCell("Token使用量统计")] }),
              new TableRow({ children: [tableCell("created_at / updated_at"), tableCell("timestamptz"), tableCell("时间戳")] }),
            ],
            width: { size: 100, type: WidthType.PERCENTAGE },
          }),
          p(""),

          h2("8.2 Token使用量累加"),
          p("两阶段解析的Token使用量在同一条记录中累加："),
          code("// 读取已有的Token统计"),
          code("const { data: existing } = await supabase"),
          code("  .from('bid_analyses').select('token_usage').eq('id', analysisId).single();"),
          code("const prev = existing?.token_usage || { prompt_tokens: 0, ... };"),
          code(""),
          code("// 累加本次使用量"),
          code("tokenData = {"),
          code("  prompt_tokens: prev.prompt_tokens + usage.prompt_tokens,"),
          code("  completion_tokens: prev.completion_tokens + usage.completion_tokens,"),
          code("  total_tokens: prev.total_tokens + usage.total_tokens,"),
          code("};"),
          p(""),

          // ===== 9. 错误处理 =====
          h1("9. 错误处理与容错设计"),

          h2("9.1 文件层面"),
          bullet("ZIP魔数校验（0x504B）— 非DOCX格式返回友好提示"),
          bullet("OLE2魔数校验（0xD0CF11E0）— 旧版.doc格式自动切换解析器"),
          bullet("文件大小限制：结构分析阶段 5MB 上限"),
          bullet("文本截断保护：超长文档自动截断并附带提示标记"),
          p(""),

          h2("9.2 AI层面"),
          bullet("JSON修复引擎（3套独立实现）— 处理截断、格式异常"),
          bullet("429/402 状态码优雅降级 — 返回空结果而非抛异常"),
          bullet("120秒 AbortController 超时保护（extract-bid-chapters）"),
          bullet("AI回退链：Lovable Pro → Lovable Flash → 自定义模型"),
          p(""),

          h2("9.3 网络层面"),
          bullet("SSE 15秒心跳包 — 防止反向代理/网关断连"),
          bullet("前端 3 秒轮询 — 即使SSE断开也能获取最终结果"),
          bullet("前端 2 分钟超时检测 — 自动标记僵死任务"),
          p(""),

          h2("9.4 数据层面"),
          bullet("结构保护机制 — 详细解析失败不影响第一阶段结构数据"),
          bullet("核心字段重试 — 数据库更新失败时去除可选字段重试"),
          bullet("暂停/继续/取消 — 用户可随时控制解析任务生命周期"),
          p(""),

          // ===== 10. 默认解析清单 =====
          h1("10. 默认解析清单"),
          p("系统预置8条解析指令，用户可自定义修改："),
          p(""),
          bullet("1. 投标截止时间，投标地点，是否讲标，投标保证金金额"),
          bullet("2. 评分标准表（分类、权重、评分细则、佐证材料）"),
          bullet("3. 废标项（★标记、否决投标条款）"),
          bullet("4. 陷阱项（容易忽略的失分条款）"),
          bullet("5. 人员配置要求（角色、数量、资质、证书）"),
          bullet("6. 专业技能/业务技能/职责关键词"),
          bullet("7. 风险评分与总体分析"),
          bullet("8. 检查招标文件中明显有逻辑错误或者冲突的内容"),
          p(""),
          p("自定义清单在用户修改后会持久化到 bid_analyses.custom_prompt 字段，重新解析时自动加载。"),
          p(""),

          // ===== 附录 =====
          h1("附录"),
          h2("A. 文件清单"),
          new Table({
            rows: [
              new TableRow({ children: [tableCell("文件路径", true, "e8e8e8"), tableCell("代码行数", true, "e8e8e8"), tableCell("职责", true, "e8e8e8")] }),
              new TableRow({ children: [tableCell("src/components/BidParser.tsx"), tableCell("~1480"), tableCell("前端交互、状态管理、结果展示")] }),
              new TableRow({ children: [tableCell("supabase/functions/parse-bid-structure/index.ts"), tableCell("~414"), tableCell("第一阶段：文档结构分析")] }),
              new TableRow({ children: [tableCell("supabase/functions/parse-bid/index.ts"), tableCell("~605"), tableCell("第二阶段：详细内容解析")] }),
              new TableRow({ children: [tableCell("supabase/functions/extract-bid-chapters/index.ts"), tableCell("~678"), tableCell("辅助：章节文本切分")] }),
            ],
            width: { size: 100, type: WidthType.PERCENTAGE },
          }),
          p(""),

          h2("B. 依赖库"),
          new Table({
            rows: [
              new TableRow({ children: [tableCell("库名", true, "e8e8e8"), tableCell("版本", true, "e8e8e8"), tableCell("位置", true, "e8e8e8"), tableCell("用途", true, "e8e8e8")] }),
              new TableRow({ children: [tableCell("fflate"), tableCell("0.8.2"), tableCell("Edge Function (npm:)"), tableCell("DOCX ZIP同步解压")] }),
              new TableRow({ children: [tableCell("xlsx"), tableCell("0.18.5"), tableCell("Edge Function (npm:)"), tableCell("Excel文件解析")] }),
              new TableRow({ children: [tableCell("word-extractor"), tableCell("1.0.4"), tableCell("Edge Function (npm:)"), tableCell("旧版.doc文件解析")] }),
              new TableRow({ children: [tableCell("DecompressionStream"), tableCell("内置"), tableCell("Edge Function"), tableCell("DOCX解压（结构分析阶段）")] }),
              new TableRow({ children: [tableCell("@supabase/supabase-js"), tableCell("2.x"), tableCell("前端+后端"), tableCell("数据库/Storage操作")] }),
            ],
            width: { size: 100, type: WidthType.PERCENTAGE },
          }),
          p(""),
          p("— 文档结束 —"),
        ],
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, "招标解析模块_详细设计说明书.docx");
}
